# Permalinks
permalink:           pretty

# Setup
title:               A Data Joint
tagline:             Just Chillin' in Utopia
url:                 http://jhonsen.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jhonsen Djajamuliadi
  url:               https://twitter.com/jhonsen_dj
  email:             kyjhons@yahoo.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jhonsen

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
